export const ProductData = [
    {
        id: 1,
        title: "Sport Shoes for Men",
        image: "/shoes/1.jpg",
        description:'Lorem ipsum ajkdas adskfjakl dsaklfaskl;f dsLorem ipsum ajkdas adskfjakl dsaklfaskl;f ds',
        price: 85,
        stock:1,
      },
      {
        id: 2,
        title: "New High Quality Shoes for Men",
        image: "/shoes/2.jpg",
        description:'Lorem ipsum ajkdas adskfjakl la;kdsfj al;sjf la;sjfklafddas',
        price: 55,
        stock:4,
      },
      {
        id: 3,
        title: "Exercise Shoes for Men",
        image: "/shoes/3.jpg",
        description:'Lorem ipsum ajkdas adskfjakl',
        price: 59,
        stock:2,
      },
      {
        id: 4,
        title: "Best Shoes",
        image: "/shoes/4.jpg",
        description:'Lorem ipsum ajkdas adskfjakl Lorem ipsum ajkdas adskfjakl dsaklfaskl;f ds',
        price: 87,
        stock:7,
      },
      {
        id: 5,
        title: "Quality Shoes",
        image: "/shoes/5.jpg",
        description:'Lorem ipsum ajkdas adskfjakl',
        price: 30,
        stock:2,
      },
      {
        id: 6,
        title: "Gray Shoes",
        image: "/shoes/6.jpg",
        description:'Lorem ipsum ajkdas adskfjakl',
        price: 70,
        stock:4,
      },
      {
        id: 7,
        title: "Casual Wearing Shoes",
        image: "/shoes/7.jpg",
        description:'Lorem ipsum ajkdas adskfjakl',
        price: 20,
        stock:5,
      },
      {
        id: 8,
        title: "Latest Trandy Shoes",
        image: "/shoes/8.jpg",
        description:'Lorem ipsum ajkdas adskfjakl',
        price: 100,
        stock:3,
      }
]